// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Chart1;
lv_obj_t * ui_Chart3;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label11;
lv_obj_t * ui_statevalue;
lv_obj_t * ui_typevalue;
lv_obj_t * ui_resisvalue;
lv_obj_t * ui_lengthvalue;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Chart2;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Button5;
lv_obj_t * ui_label_log;
lv_obj_t * label_chart;
lv_obj_t * label_chart2;
lv_obj_t * ui_tdr_switch;
lv_obj_t * ui_k_cable_spinbox;
lv_chart_cursor_t * spectrum_cursor;
lv_chart_series_t * ui_Chart3_mag;
lv_chart_series_t * ui_Chart3_phase;
lv_chart_series_t * ui_Chart2_smith;
lv_chart_series_t * ui_Chart3_tdr;
lv_obj_t * btn_test;
lv_obj_t * ui_correct_switch;
//lv_obj_t *
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
