// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <complex.h>

#include "lvgl.h"
//#include "myfile_display.h"
#include "ui_helpers.h"
#include "ui_events.h"

#define UI_STATE_IDLE 0
#define UI_STATE_TEST 1
#define UI_STATE_LENGTH 2
#define UI_STATE_LOAD 3

#define UI_LOAD_CAP 1
#define UI_LOAD_RES 2
#define UI_LOAD_OPEN 3
#define UI_LOAD_NONE 4
#define UI_LOAD_L 5 //TODO ZH  电感

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_statevalue;
extern lv_obj_t * ui_typevalue;
extern lv_obj_t * ui_resisvalue;
extern lv_obj_t * ui_lengthvalue;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button5;
extern lv_chart_cursor_t * spectrum_cursor;
extern lv_chart_series_t * ui_Chart3_mag;
extern lv_chart_series_t * ui_Chart3_phase;
extern lv_chart_series_t * ui_Chart2_smith;
extern lv_chart_series_t * ui_Chart3_tdr;
extern lv_obj_t * ui_label_log;
extern lv_obj_t * label_chart;
extern lv_obj_t * label_chart2;
extern lv_obj_t * ui_tdr_switch;
extern lv_obj_t * ui_k_cable_spinbox;
extern lv_obj_t * btn_test;
extern lv_obj_t * ui_correct_switch;
extern lv_obj_t * ui____initial_actions0;
// extern uint8_t length_flag;

void set_load_type(uint8_t type,float value);

//data是TDR时域波形数据，size为长度，t_max最大时间
//对于下标为index的点，t=index/size*t_max   ,   x=t*c_light*k_cable
void draw_tdr(float *data,uint16_t size,float t_max);
//void ui_all_wave_show(void);
void draw_smith(uint16_t size,float complex *s11);
void draw_spec(uint16_t size,uint32_t freq_l,uint32_t freq_h,float complex *s11);
uint8_t get_correct_state();
void check_tdr();
uint8_t get_ui_state();
void set_ui_state(uint8_t state);

LV_IMG_DECLARE(ui_img_smith_png);    // assets\smith.png

LV_FONT_DECLARE(ui_font_SourceHanSansCN);
LV_FONT_DECLARE(ui_font_SourceHanSansCN15);
LV_FONT_DECLARE(lv_font_MiSans_Normal_22);
LV_FONT_DECLARE(lv_font_MiSans_Normal_18);
void ui_init(void);
void draw_smith_Demo();
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
